from langchain_openai import ChatOpenAI
from dotenv import load_dotenv

load_dotenv()

model = ChatOpenAI(model="gpt-4", temperature=1.0 , max_completion_tokens=5)
#temperature is randomness or creativity in the model
#temperature 0.0 means model is not creative and will always give same output
#temperature 1.0 means model is creative and will always give different output

#max_completion_tokens is the maximum number of tokens that can be generated by the model

print(model.invoke("What is the capital of india?").content)
 