from langchain_openai import ChatOpenAI
from dotenv import load_dotenv

load_dotenv()

model = ChatOpenAI(model="gpt-4", temperature=1.0 , max_completion_tokens=5)
#temperature is randomness in the model
#max_completion_tokens is the maximum number of tokens that can be generated by the model

print(model.invoke("What is the capital of india?").content)
